---
title: "Version Control"
date: 2022-01-25T18:55:11+01:00
draft: true
weight: 10
---

There are several version control systems on the market, usually teams rely on text based version
control like `Git`, `Mercurial` or `Subversion`. Depending on your code hosting platform
https://github.com[GitHub,window=_blank], https://gitlab.com[GitLab,window=_blank],
https://bitbucket.org[Bitbucket,window=_blank] you'll have support for one or several of these
version control systems.

[NOTE]
====
Ideally all teams use the same version control system to avoid the overhead of maintaining different
development environments for different components.
====

The use of a version control system helps the team to meet the requirement of *traceability* and
*reproducibility*.

The team must be familiar with the usual operations of creating a _branch_, _pulling_ and _merging_
changes, _resolving conflicts_.

More information in the manual of your version control system:

* https://git-scm.com/docs/user-manual.html[Git,window=_blank]
* https://www.mercurial-scm.org/guide[Mercurial,window=_blank]
* https://www.mercurial-scm.org/guide[Subversion,window=_blank]

== What to put under version control?

A usual problem is to use version control only to the source code of the main
application/components, leaving the rest of infrastructure code (scripts, templates, configuration)
out of version control. The team should use version control for all code required to build a
production environment.

Example of infrastructure code in the same code repository:

* https://github.com/facebook/react/blob/v17.0.2/scripts/release/publish-commands/publish-to-npm.js#L37[React.js,window=_blank]
* https://github.com/OpenFn/microservice/tree/v0.3.3/kubernetes[OpenFn,window=_blank]
* https://github.com/akvo/unep-gpml/tree/main/ci[UNEP-GPML,window=_blank]
