name: hugo

on:
  push:
  pull_request:

jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run Hugo
        uses: crazy-max/ghaction-hugo@v3
        with:
          version: latest
          extended: false
          args: --cleanDestinationDir --minify --verbose
      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
